//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeaturesPimServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", ConfigurationName="FeaturesPimServiceReference.FeaturesPIM_Port")]
    public interface FeaturesPIM_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.Read_Result> ReadAsync(FeaturesPimServiceReference.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.ReadByRecId_Result> ReadByRecIdAsync(FeaturesPimServiceReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.ReadMultiple_Result> ReadMultipleAsync(FeaturesPimServiceReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.IsUpdated_Result> IsUpdatedAsync(FeaturesPimServiceReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(FeaturesPimServiceReference.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.Create_Result> CreateAsync(FeaturesPimServiceReference.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.CreateMultiple_Result> CreateMultipleAsync(FeaturesPimServiceReference.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.Update_Result> UpdateAsync(FeaturesPimServiceReference.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.UpdateMultiple_Result> UpdateMultipleAsync(FeaturesPimServiceReference.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/featurespim:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.Delete_Result> DeleteAsync(FeaturesPimServiceReference.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public partial class FeaturesPIM
    {
        
        private string keyField;
        
        private string group_System_NumberField;
        
        private Line_Type line_TypeField;
        
        private bool line_TypeFieldSpecified;
        
        private string numberField;
        
        private string descriptionField;
        
        private string valueField;
        
        private string unit_IDField;
        
        private int valuesField;
        
        private bool valuesFieldSpecified;
        
        private int possible_valuesField;
        
        private bool possible_valuesFieldSpecified;
        
        private Field_Type field_TypeField;
        
        private bool field_TypeFieldSpecified;
        
        private string usage_Type_CodeField;
        
        private Feature_Type feature_TypeField;
        
        private bool feature_TypeFieldSpecified;
        
        private Source_Type source_TypeField;
        
        private bool source_TypeFieldSpecified;
        
        private string source_CodeField;
        
        private bool not_inheritance_valueField;
        
        private bool not_inheritance_valueFieldSpecified;
        
        private string composed_valueField;
        
        private string connection_CharacteristicsField;
        
        private Formatting formattingField;
        
        private bool formattingFieldSpecified;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        private string search_Feature_IDField;
        
        private string feature_ID_ReferenceField;
        
        private string document_IDField;
        
        private string field_FormatField;
        
        private Alignment alignmentField;
        
        private bool alignmentFieldSpecified;
        
        private Output_Format_Features output_Format_FeaturesField;
        
        private bool output_Format_FeaturesFieldSpecified;
        
        private Print printField;
        
        private bool printFieldSpecified;
        
        private Web webField;
        
        private bool webFieldSpecified;
        
        private bool description_TextsField;
        
        private bool description_TextsFieldSpecified;
        
        private string unit_Shorthand_DescriptionField;
        
        private string value_IDField;
        
        private string value_ID_ReferenceField;
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Group_System_Number
        {
            get
            {
                return this.group_System_NumberField;
            }
            set
            {
                this.group_System_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Line_Type Line_Type
        {
            get
            {
                return this.line_TypeField;
            }
            set
            {
                this.line_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_TypeSpecified
        {
            get
            {
                return this.line_TypeFieldSpecified;
            }
            set
            {
                this.line_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Unit_ID
        {
            get
            {
                return this.unit_IDField;
            }
            set
            {
                this.unit_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValuesSpecified
        {
            get
            {
                return this.valuesFieldSpecified;
            }
            set
            {
                this.valuesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Possible_values
        {
            get
            {
                return this.possible_valuesField;
            }
            set
            {
                this.possible_valuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Possible_valuesSpecified
        {
            get
            {
                return this.possible_valuesFieldSpecified;
            }
            set
            {
                this.possible_valuesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Field_Type Field_Type
        {
            get
            {
                return this.field_TypeField;
            }
            set
            {
                this.field_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Field_TypeSpecified
        {
            get
            {
                return this.field_TypeFieldSpecified;
            }
            set
            {
                this.field_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Usage_Type_Code
        {
            get
            {
                return this.usage_Type_CodeField;
            }
            set
            {
                this.usage_Type_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Feature_Type Feature_Type
        {
            get
            {
                return this.feature_TypeField;
            }
            set
            {
                this.feature_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Feature_TypeSpecified
        {
            get
            {
                return this.feature_TypeFieldSpecified;
            }
            set
            {
                this.feature_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Source_Type Source_Type
        {
            get
            {
                return this.source_TypeField;
            }
            set
            {
                this.source_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_TypeSpecified
        {
            get
            {
                return this.source_TypeFieldSpecified;
            }
            set
            {
                this.source_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Source_Code
        {
            get
            {
                return this.source_CodeField;
            }
            set
            {
                this.source_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool Not_inheritance_value
        {
            get
            {
                return this.not_inheritance_valueField;
            }
            set
            {
                this.not_inheritance_valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Not_inheritance_valueSpecified
        {
            get
            {
                return this.not_inheritance_valueFieldSpecified;
            }
            set
            {
                this.not_inheritance_valueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Composed_value
        {
            get
            {
                return this.composed_valueField;
            }
            set
            {
                this.composed_valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Connection_Characteristics
        {
            get
            {
                return this.connection_CharacteristicsField;
            }
            set
            {
                this.connection_CharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public Formatting Formatting
        {
            get
            {
                return this.formattingField;
            }
            set
            {
                this.formattingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FormattingSpecified
        {
            get
            {
                return this.formattingFieldSpecified;
            }
            set
            {
                this.formattingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool Required
        {
            get
            {
                return this.requiredField;
            }
            set
            {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiredSpecified
        {
            get
            {
                return this.requiredFieldSpecified;
            }
            set
            {
                this.requiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Search_Feature_ID
        {
            get
            {
                return this.search_Feature_IDField;
            }
            set
            {
                this.search_Feature_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Feature_ID_Reference
        {
            get
            {
                return this.feature_ID_ReferenceField;
            }
            set
            {
                this.feature_ID_ReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Document_ID
        {
            get
            {
                return this.document_IDField;
            }
            set
            {
                this.document_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Field_Format
        {
            get
            {
                return this.field_FormatField;
            }
            set
            {
                this.field_FormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public Alignment Alignment
        {
            get
            {
                return this.alignmentField;
            }
            set
            {
                this.alignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlignmentSpecified
        {
            get
            {
                return this.alignmentFieldSpecified;
            }
            set
            {
                this.alignmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public Output_Format_Features Output_Format_Features
        {
            get
            {
                return this.output_Format_FeaturesField;
            }
            set
            {
                this.output_Format_FeaturesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Output_Format_FeaturesSpecified
        {
            get
            {
                return this.output_Format_FeaturesFieldSpecified;
            }
            set
            {
                this.output_Format_FeaturesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public Print Print
        {
            get
            {
                return this.printField;
            }
            set
            {
                this.printField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrintSpecified
        {
            get
            {
                return this.printFieldSpecified;
            }
            set
            {
                this.printFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public Web Web
        {
            get
            {
                return this.webField;
            }
            set
            {
                this.webField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WebSpecified
        {
            get
            {
                return this.webFieldSpecified;
            }
            set
            {
                this.webFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool Description_Texts
        {
            get
            {
                return this.description_TextsField;
            }
            set
            {
                this.description_TextsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Description_TextsSpecified
        {
            get
            {
                return this.description_TextsFieldSpecified;
            }
            set
            {
                this.description_TextsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Unit_Shorthand_Description
        {
            get
            {
                return this.unit_Shorthand_DescriptionField;
            }
            set
            {
                this.unit_Shorthand_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Value_ID
        {
            get
            {
                return this.value_IDField;
            }
            set
            {
                this.value_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Value_ID_Reference
        {
            get
            {
                return this.value_ID_ReferenceField;
            }
            set
            {
                this.value_ID_ReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public int Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified
        {
            get
            {
                return this.orderFieldSpecified;
            }
            set
            {
                this.orderFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum Line_Type
    {
        
        /// <remarks/>
        Feature,
        
        /// <remarks/>
        Feature_Group,
        
        /// <remarks/>
        Title,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum Field_Type
    {
        
        /// <remarks/>
        numerisch,
        
        /// <remarks/>
        alphanumerisch,
        
        /// <remarks/>
        logisch,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum Feature_Type
    {
        
        /// <remarks/>
        Basis,
        
        /// <remarks/>
        Ausstattung,
        
        /// <remarks/>
        Technik,
        
        /// <remarks/>
        Leistung,
        
        /// <remarks/>
        Specification,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum Source_Type
    {
        
        /// <remarks/>
        Artikel,
        
        /// <remarks/>
        Artikelgruppe,
        
        /// <remarks/>
        Klasse,
        
        /// <remarks/>
        Warengruppe,
        
        /// <remarks/>
        Kapitel,
        
        /// <remarks/>
        Kataloggruppe,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum Formatting
    {
        
        /// <remarks/>
        keine,
        
        /// <remarks/>
        Leerzeichen_links,
        
        /// <remarks/>
        Leerzeichen_rechts,
        
        /// <remarks/>
        Leerzeichen_beiderseits,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum Alignment
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        horizontal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum Output_Format_Features
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Einheit,
        
        /// <remarks/>
        Einheit_mit_Klammern,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum Print
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum Web
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public partial class FeaturesPIM_Filter
    {
        
        private FeaturesPIM_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FeaturesPIM_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim")]
    public enum FeaturesPIM_Fields
    {
        
        /// <remarks/>
        Group_System_Number,
        
        /// <remarks/>
        Line_Type,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Value,
        
        /// <remarks/>
        Unit_ID,
        
        /// <remarks/>
        Values,
        
        /// <remarks/>
        Possible_values,
        
        /// <remarks/>
        Field_Type,
        
        /// <remarks/>
        Usage_Type_Code,
        
        /// <remarks/>
        Feature_Type,
        
        /// <remarks/>
        Source_Type,
        
        /// <remarks/>
        Source_Code,
        
        /// <remarks/>
        Not_inheritance_value,
        
        /// <remarks/>
        Composed_value,
        
        /// <remarks/>
        Connection_Characteristics,
        
        /// <remarks/>
        Formatting,
        
        /// <remarks/>
        Required,
        
        /// <remarks/>
        Search_Feature_ID,
        
        /// <remarks/>
        Feature_ID_Reference,
        
        /// <remarks/>
        Document_ID,
        
        /// <remarks/>
        Field_Format,
        
        /// <remarks/>
        Alignment,
        
        /// <remarks/>
        Output_Format_Features,
        
        /// <remarks/>
        Print,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Description_Texts,
        
        /// <remarks/>
        Unit_Shorthand_Description,
        
        /// <remarks/>
        Value_ID,
        
        /// <remarks/>
        Value_ID_Reference,
        
        /// <remarks/>
        Order,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public string Group_System_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=1)]
        public string Source_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=2)]
        public string Source_Code;
        
        public Read()
        {
        }
        
        public Read(string Group_System_Number, string Source_Type, string Source_Code)
        {
            this.Group_System_Number = Group_System_Number;
            this.Source_Type = Source_Type;
            this.Source_Code = Source_Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public FeaturesPimServiceReference.FeaturesPIM FeaturesPIM;
        
        public Read_Result()
        {
        }
        
        public Read_Result(FeaturesPimServiceReference.FeaturesPIM FeaturesPIM)
        {
            this.FeaturesPIM = FeaturesPIM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public FeaturesPimServiceReference.FeaturesPIM FeaturesPIM;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(FeaturesPimServiceReference.FeaturesPIM FeaturesPIM)
        {
            this.FeaturesPIM = FeaturesPIM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public FeaturesPimServiceReference.FeaturesPIM_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(FeaturesPimServiceReference.FeaturesPIM_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FeaturesPimServiceReference.FeaturesPIM[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(FeaturesPimServiceReference.FeaturesPIM[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public FeaturesPimServiceReference.FeaturesPIM FeaturesPIM;
        
        public Create()
        {
        }
        
        public Create(FeaturesPimServiceReference.FeaturesPIM FeaturesPIM)
        {
            this.FeaturesPIM = FeaturesPIM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public FeaturesPimServiceReference.FeaturesPIM FeaturesPIM;
        
        public Create_Result()
        {
        }
        
        public Create_Result(FeaturesPimServiceReference.FeaturesPIM FeaturesPIM)
        {
            this.FeaturesPIM = FeaturesPIM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FeaturesPimServiceReference.FeaturesPIM[] FeaturesPIM_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(FeaturesPimServiceReference.FeaturesPIM[] FeaturesPIM_List)
        {
            this.FeaturesPIM_List = FeaturesPIM_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FeaturesPimServiceReference.FeaturesPIM[] FeaturesPIM_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(FeaturesPimServiceReference.FeaturesPIM[] FeaturesPIM_List)
        {
            this.FeaturesPIM_List = FeaturesPIM_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public FeaturesPimServiceReference.FeaturesPIM FeaturesPIM;
        
        public Update()
        {
        }
        
        public Update(FeaturesPimServiceReference.FeaturesPIM FeaturesPIM)
        {
            this.FeaturesPIM = FeaturesPIM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public FeaturesPimServiceReference.FeaturesPIM FeaturesPIM;
        
        public Update_Result()
        {
        }
        
        public Update_Result(FeaturesPimServiceReference.FeaturesPIM FeaturesPIM)
        {
            this.FeaturesPIM = FeaturesPIM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FeaturesPimServiceReference.FeaturesPIM[] FeaturesPIM_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(FeaturesPimServiceReference.FeaturesPIM[] FeaturesPIM_List)
        {
            this.FeaturesPIM_List = FeaturesPIM_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FeaturesPimServiceReference.FeaturesPIM[] FeaturesPIM_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(FeaturesPimServiceReference.FeaturesPIM[] FeaturesPIM_List)
        {
            this.FeaturesPIM_List = FeaturesPIM_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/featurespim", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/featurespim", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface FeaturesPIM_PortChannel : FeaturesPimServiceReference.FeaturesPIM_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class FeaturesPIM_PortClient : System.ServiceModel.ClientBase<FeaturesPimServiceReference.FeaturesPIM_Port>, FeaturesPimServiceReference.FeaturesPIM_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FeaturesPIM_PortClient(System.Uri uri) : 
                base(FeaturesPIM_PortClient.GetDefaultBinding(), FeaturesPIM_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FeaturesPIM_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FeaturesPIM_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(FeaturesPIM_PortClient.GetBindingForEndpoint(endpointConfiguration), FeaturesPIM_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FeaturesPIM_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FeaturesPIM_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FeaturesPIM_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FeaturesPIM_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FeaturesPIM_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.Read_Result> FeaturesPimServiceReference.FeaturesPIM_Port.ReadAsync(FeaturesPimServiceReference.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.Read_Result> ReadAsync(string Group_System_Number, string Source_Type, string Source_Code)
        {
            FeaturesPimServiceReference.Read inValue = new FeaturesPimServiceReference.Read();
            inValue.Group_System_Number = Group_System_Number;
            inValue.Source_Type = Source_Type;
            inValue.Source_Code = Source_Code;
            return ((FeaturesPimServiceReference.FeaturesPIM_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.ReadByRecId_Result> FeaturesPimServiceReference.FeaturesPIM_Port.ReadByRecIdAsync(FeaturesPimServiceReference.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            FeaturesPimServiceReference.ReadByRecId inValue = new FeaturesPimServiceReference.ReadByRecId();
            inValue.recId = recId;
            return ((FeaturesPimServiceReference.FeaturesPIM_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.ReadMultiple_Result> FeaturesPimServiceReference.FeaturesPIM_Port.ReadMultipleAsync(FeaturesPimServiceReference.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.ReadMultiple_Result> ReadMultipleAsync(FeaturesPimServiceReference.FeaturesPIM_Filter[] filter, string bookmarkKey, int setSize)
        {
            FeaturesPimServiceReference.ReadMultiple inValue = new FeaturesPimServiceReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((FeaturesPimServiceReference.FeaturesPIM_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.IsUpdated_Result> FeaturesPimServiceReference.FeaturesPIM_Port.IsUpdatedAsync(FeaturesPimServiceReference.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            FeaturesPimServiceReference.IsUpdated inValue = new FeaturesPimServiceReference.IsUpdated();
            inValue.Key = Key;
            return ((FeaturesPimServiceReference.FeaturesPIM_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.GetRecIdFromKey_Result> FeaturesPimServiceReference.FeaturesPIM_Port.GetRecIdFromKeyAsync(FeaturesPimServiceReference.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            FeaturesPimServiceReference.GetRecIdFromKey inValue = new FeaturesPimServiceReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((FeaturesPimServiceReference.FeaturesPIM_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.Create_Result> CreateAsync(FeaturesPimServiceReference.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.CreateMultiple_Result> CreateMultipleAsync(FeaturesPimServiceReference.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.Update_Result> UpdateAsync(FeaturesPimServiceReference.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.UpdateMultiple_Result> UpdateMultipleAsync(FeaturesPimServiceReference.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FeaturesPimServiceReference.Delete_Result> FeaturesPimServiceReference.FeaturesPIM_Port.DeleteAsync(FeaturesPimServiceReference.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FeaturesPimServiceReference.Delete_Result> DeleteAsync(string Key)
        {
            FeaturesPimServiceReference.Delete inValue = new FeaturesPimServiceReference.Delete();
            inValue.Key = Key;
            return ((FeaturesPimServiceReference.FeaturesPIM_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FeaturesPIM_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FeaturesPIM_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://pimicschatbot.westeurope.cloudapp.azure.com:7047/NAV/WS/CRONUS Internation" +
                        "al Ltd./Page/FeaturesPIM");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FeaturesPIM_PortClient.GetBindingForEndpoint(EndpointConfiguration.FeaturesPIM_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FeaturesPIM_PortClient.GetEndpointAddress(EndpointConfiguration.FeaturesPIM_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            FeaturesPIM_Port,
        }
    }
}
